flowchart TD
x23 & y23 --> mhq[AND mhq]
x33 & y33 --> pvc[AND pvc]
x33 & y33 --> jbr[XOR jbr]
y32 & x32 --> rjq[AND rjq]
x31 & y31 --> kbv[XOR kbv]
y29 & x29 --> wft[XOR wft]
y28 & x28 --> wgd[AND wgd]
x27 & y27 --> jns[AND jns]
x27 & y27 --> mcv[XOR mcv]
x25 & y25 --> tvb[XOR tvb]
y24 & x24 --> tbn[AND tbn]
y22 & x22 --> nrq[AND nrq]
x22 & y22 --> jkq[XOR jkq]
x21 & y21 --> bbn[XOR bbn]
y18 & x18 --> sdp[AND sdp]
y17 & x17 --> nhh[AND nhh]
y17 & x17 --> nqm[XOR nqm]
x15 & y15 --> srk[XOR srk]
y14 & x14 --> dwt[AND dwt]
y13 & x13 --> ggg[AND ggg]
x12 & y12 --> vdc[AND vdc]
y11 & x11 --> rvg[AND rvg]
x10 & y10 --> ptj[AND ptj]
x09 & y09 --> bsm[AND bsm]
y06 & x06 --> cnm[AND cnm]
x06 & y06 --> bgq[XOR bgq]
x05 & y05 --> chs[XOR chs]
y03 & x03 --> ssj[AND ssj]
y03 & x03 --> fpk[XOR fpk]
y01 & x01 --> gpk[XOR gpk]
y00 & x00 --> spq[AND spq]
gpk & spq --> bvk[AND bvk]
y01 & x01 --> khh[AND khh]
bvk & khh --> nmw[OR nmw]
x02 & y02 --> bgp[XOR bgp]
nmw & bgp --> bcr[AND bcr]
y02 & x02 --> psw[AND psw]
bcr & psw --> dfh[OR dfh]
fpk & dfh --> ccr[AND ccr]
ssj & ccr --> qfk[OR qfk]
y04 & x04 --> pvj[XOR pvj]
qfk & pvj --> ndp[AND ndp]
y04 & x04 --> nfq[AND nfq]
ndp & nfq --> rgv[OR rgv]
chs & rgv --> jhv[AND jhv]
y05 & x05 --> nph[AND nph]
jhv & nph --> wdh[OR wdh]
bgq & wdh --> dgh[AND dgh]
cnm & dgh --> pmv[OR pmv]
x07 & y07 --> gqg[XOR gqg]
pmv & gqg --> dbm[AND dbm]
y07 & x07 --> jft[AND jft]
dbm & jft --> qtg[OR qtg]
x08 & y08 --> knh[XOR knh]
qtg & knh --> ccd[AND ccd]
y08 & x08 --> cst[AND cst]
ccd & cst --> cbk[OR cbk]
x09 & y09 --> nbm[XOR nbm]
cbk & nbm --> vsc[AND vsc]
bsm & vsc --> fjn[OR fjn]
x10 & y10 --> htc[XOR htc]
fjn & htc --> dtg[AND dtg]
ptj & dtg --> spg[OR spg]
x11 & y11 --> hhm[XOR hhm]
spg & hhm --> wvv[AND wvv]
rvg & wvv --> wdg[OR wdg]
x12 & y12 --> pps[XOR pps]
wdg & pps --> kcp[AND kcp]
vdc & kcp --> fbk[OR fbk]
x13 & y13 --> tcq[XOR tcq]
fbk & tcq --> hvg[AND hvg]
ggg & hvg --> csf[OR csf]
x14 & y14 --> bck[XOR bck]
csf & bck --> qsg[AND qsg]
dwt & qsg --> sjm[OR sjm]
srk & sjm --> fwg[AND fwg]
x15 & y15 --> gtf[AND gtf]
fwg & gtf --> rrj[OR rrj]
x16 & y16 --> mft[XOR mft]
rrj & mft --> tnt[AND tnt]
x16 & y16 --> khn[AND khn]
tnt & khn --> fmf[OR fmf]
nqm & fmf --> tgq[AND tgq]
nhh & tgq --> jmr[OR jmr]
y18 & x18 --> nhm[XOR nhm]
jmr & nhm --> ptd[AND ptd]
sdp & ptd --> rtg[OR rtg]
y19 & x19 --> kfd[XOR kfd]
rtg & kfd --> dmb[AND dmb]
x19 & y19 --> crv[AND crv]
dmb & crv --> ddw[OR ddw]
x20 & y20 --> fht[XOR fht]
ddw & fht --> qfn[AND qfn]
x20 & y20 --> fct[AND fct]
qfn & fct --> rsc[OR rsc]
bbn & rsc --> cdc[AND cdc]
x21 & y21 --> stq[AND stq]
cdc & stq --> nhn[OR nhn]
jkq & nhn --> vkg[AND vkg]
nrq & vkg --> mmw[OR mmw]
x23 & y23 --> ncf[XOR ncf]
mmw & ncf --> rkf[AND rkf]
rkf & mhq --> rqd[OR rqd]
x24 & y24 --> cns[XOR cns]
rqd & cns --> grb[AND grb]
tbn & grb --> jhd[OR jhd]
tvb & jhd --> rcb[AND rcb]
y25 & x25 --> khg[AND khg]
rcb & khg --> mfp[OR mfp]
x26 & y26 --> spf[XOR spf]
mfp & spf --> gqb[AND gqb]
y26 & x26 --> csh[AND csh]
gqb & csh --> mbp[OR mbp]
mcv & mbp --> npn[AND npn]
jns & npn --> jbv[OR jbv]
x28 & y28 --> kjg[XOR kjg]
jbv & kjg --> vjg[AND vjg]
wgd & vjg --> nnq[OR nnq]
wft & nnq --> stm[AND stm]
y29 & x29 --> tjt[AND tjt]
stm & tjt --> gsj[OR gsj]
x30 & y30 --> ftw[XOR ftw]
gsj & ftw --> pwp[AND pwp]
y30 & x30 --> nmj[AND nmj]
pwp & nmj --> ctw[OR ctw]
kbv & ctw --> qhg[AND qhg]
x31 & y31 --> gnc[AND gnc]
qhg & gnc --> fqc[OR fqc]
x32 & y32 --> cpt[XOR cpt]
fqc & cpt --> nfh[AND nfh]
rjq & nfh --> wcs[OR wcs]
jbr & wcs --> gst[AND gst]
pvc & gst --> kmm[OR kmm]
x34 & y34 --> ptk[XOR ptk]
kmm & ptk --> vnr[AND vnr]
y34 & x34 --> krb[AND krb]
vnr & krb --> dbf[OR dbf]
y35 & x35 --> dsb[XOR dsb]
dbf & dsb --> z35[XOR z35]
x41 & y41 --> qss[AND qss]
x42 & y42 --> djs[AND djs]
y42 & x42 --> vbq[XOR vbq]
y39 & x39 --> cbf[AND cbf]
y39 & x39 --> fgc[XOR fgc]
x38 & y38 --> tvm[XOR tvm]
x37 & y37 --> hbr[XOR hbr]
x36 & y36 --> jbq[AND jbq]
x36 & y36 --> fcf[XOR fcf]
x35 & y35 --> jdk[AND jdk]
dbf & dsb --> pmr[AND pmr]
jdk & pmr --> spk[OR spk]
fcf & spk --> vmj[AND vmj]
jbq & vmj --> qfp[OR qfp]
hbr & qfp --> mjr[AND mjr]
y37 & x37 --> kpb[AND kpb]
mjr & kpb --> pkw[OR pkw]
tvm & pkw --> tvc[AND tvc]
x38 & y38 --> dcc[AND dcc]
tvc & dcc --> dvm[OR dvm]
fgc & dvm --> nfn[AND nfn]
cbf & nfn --> fvh[OR fvh]
y40 & x40 --> pgc[XOR pgc]
fvh & pgc --> hdq[AND hdq]
x40 & y40 --> gdm[AND gdm]
hdq & gdm --> fdv[OR fdv]
x41 & y41 --> dfs[XOR dfs]
fdv & dfs --> wtt[AND wtt]
qss & wtt --> bwv[OR bwv]
vbq & bwv --> tgk[AND tgk]
djs & tgk --> ccp[OR ccp]
tvb & jhd --> z25[XOR z25]
tvm & pkw --> z38[XOR z38]
x44 & y44 --> vwd[XOR vwd]
y43 & x43 --> pkj[AND pkj]
y43 & x43 --> hhg[XOR hhg]
hhg & ccp --> msp[AND msp]
pkj & msp --> kvv[OR kvv]
vwd & kvv --> mgw[AND mgw]
nmw & bgp --> z02[XOR z02]
fht & ddw --> z20[XOR z20]
gqg & pmv --> z07[XOR z07]
bwv & vbq --> z42[XOR z42]
kbv & ctw --> z31[XOR z31]
mmw & ncf --> z23[XOR z23]
wft & nnq --> z29[XOR z29]
rrj & mft --> z16[XOR z16]
y00 & x00 --> z00[XOR z00]
pps & wdg --> z12[XOR z12]
nhm & jmr --> z18[XOR z18]
kfd & rtg --> z19[XOR z19]
cpt & fqc --> z32[XOR z32]
spq & gpk --> z01[XOR z01]
mfp & spf --> z26[XOR z26]
spg & hhm --> z11[XOR z11]
fmf & nqm --> z17[XOR z17]
fvh & pgc --> z40[XOR z40]
fcf & spk --> z36[XOR z36]
ptk & kmm --> z34[XOR z34]
kvv & vwd --> z44[XOR z44]
wcs & jbr --> z33[XOR z33]
srk & sjm --> z15[XOR z15]
bgq & wdh --> z06[XOR z06]
jbv & kjg --> z28[XOR z28]
ccp & hhg --> z43[XOR z43]
ftw & gsj --> z30[XOR z30]
x44 & y44 --> bds[AND bds]
fjn & htc --> z10[XOR z10]
mgw & bds --> z45[OR z45]
pvj & qfk --> z04[XOR z04]
jkq & nhn --> z22[XOR z22]
chs & rgv --> z05[XOR z05]
knh & qtg --> z08[XOR z08]
hbr & qfp --> z37[XOR z37]
dfs & fdv --> z41[XOR z41]
dvm & fgc --> z39[XOR z39]
cns & rqd --> z24[XOR z24]
dfh & fpk --> z03[XOR z03]
fbk & tcq --> z13[XOR z13]
mcv & mbp --> z27[XOR z27]
nbm & cbk --> z09[XOR z09]
rsc & bbn --> z21[XOR z21]
bck & csf --> z14[XOR z14]
